import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { calculateBMR, calculateTDEE, calculateAge, calculateProteinRange } from '@/lib/bmr-utils';
import { FileText, Download } from 'lucide-react';

interface Props { userId: string; }

interface MedicalData {
  fullName: string;
  age: number;
  weight: number;
  height: number;
  bmr: number;
  tdee: number;
  goalWeight: number | null;
  bodyLogs: { logged_at: string; weight: number | null; body_fat_pct: number | null; waist_cm: number | null }[];
  checkins: { logged_at: string; sleep_quality: number; energy_level: number; appetite: number; mood: number }[];
}

const MedicalDashboard = ({ userId }: Props) => {
  const [data, setData] = useState<MedicalData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      const { data: profile } = await supabase.from('profiles').select('*').eq('user_id', userId).single();
      if (!profile?.current_weight || !profile?.height_cm || !profile?.birth_date) {
        setLoading(false);
        return;
      }

      const age = calculateAge(profile.birth_date);
      const bmr = calculateBMR(profile.current_weight, profile.height_cm, age);
      const tdee = calculateTDEE(bmr, profile.activity_level || 'sedentary', profile.adaptive_metabolism);

      const { data: bodyLogs } = await supabase
        .from('body_composition_logs')
        .select('logged_at, weight, body_fat_pct, waist_cm')
        .eq('user_id', userId)
        .order('logged_at', { ascending: false })
        .limit(20);

      const { data: checkins } = await supabase
        .from('daily_checkins')
        .select('logged_at, sleep_quality, energy_level, appetite, mood')
        .eq('user_id', userId)
        .order('logged_at', { ascending: false })
        .limit(14);

      setData({
        fullName: profile.full_name,
        age,
        weight: profile.current_weight,
        height: profile.height_cm,
        bmr: Math.round(bmr),
        tdee,
        goalWeight: profile.goal_weight,
        bodyLogs: bodyLogs || [],
        checkins: checkins || [],
      });
      setLoading(false);
    };
    load();
  }, [userId]);

  const exportPDF = () => {
    if (!data) return;

    const protein = calculateProteinRange(data.weight);
    const lines = [
      '═══════════════════════════════════════════',
      '         MY GLOWFIT — MEDICAL REPORT       ',
      '═══════════════════════════════════════════',
      '',
      `Patient: ${data.fullName}`,
      `Date: ${new Date().toLocaleDateString()}`,
      `Age: ${data.age} years`,
      '',
      '── METABOLIC PROFILE ──',
      `Weight: ${data.weight} kg`,
      `Height: ${data.height} cm`,
      `BMI: ${(data.weight / ((data.height / 100) ** 2)).toFixed(1)}`,
      `BMR: ${data.bmr} kcal/day`,
      `TDEE: ${data.tdee} kcal/day`,
      `Goal Weight: ${data.goalWeight ?? 'Not set'} kg`,
      `Recommended Protein: ${protein.min}–${protein.max}g/day`,
      '',
      '── BODY COMPOSITION HISTORY ──',
      'Date         | Weight | Body Fat % | Waist',
      ...data.bodyLogs.map((l) =>
        `${new Date(l.logged_at).toLocaleDateString().padEnd(13)}| ${(l.weight?.toString() ?? '-').padEnd(7)}| ${(l.body_fat_pct?.toString() ?? '-').padEnd(11)}| ${l.waist_cm ?? '-'} cm`
      ),
      '',
      '── DAILY WELLNESS CHECK-INS ──',
      'Date         | Sleep | Energy | Appetite | Mood',
      ...data.checkins.map((c) =>
        `${new Date(c.logged_at).toLocaleDateString().padEnd(13)}| ${String(c.sleep_quality).padEnd(6)}| ${String(c.energy_level).padEnd(7)}| ${String(c.appetite).padEnd(9)}| ${c.mood}`
      ),
      '',
      '═══════════════════════════════════════════',
      'Generated by My Glowfit · For medical use',
      '═══════════════════════════════════════════',
    ];

    const text = lines.join('\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MyGlowfit_Medical_Report_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) return <Card><CardContent className="py-8 text-center text-muted-foreground">Loading medical data...</CardContent></Card>;

  if (!data) {
    return (
      <Card>
        <CardContent className="py-8 text-center">
          <p className="text-muted-foreground">Complete your metabolic profile first to generate a medical report.</p>
        </CardContent>
      </Card>
    );
  }

  const bmi = (data.weight / ((data.height / 100) ** 2)).toFixed(1);
  const protein = calculateProteinRange(data.weight);

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <FileText className="h-4 w-4 text-primary" />
            Medical Dashboard
          </CardTitle>
          <p className="text-xs text-muted-foreground">Summary for healthcare providers</p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <Stat label="BMI" value={bmi} />
            <Stat label="BMR" value={`${data.bmr} kcal`} />
            <Stat label="TDEE" value={`${data.tdee} kcal`} />
            <Stat label="Protein" value={`${protein.min}–${protein.max}g`} />
          </div>

          {data.bodyLogs.length > 0 && (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-2">Last {data.bodyLogs.length} Body Measurements</p>
              <div className="space-y-1">
                {data.bodyLogs.slice(0, 5).map((l, i) => (
                  <div key={i} className="flex justify-between text-xs border-b border-border pb-1">
                    <span className="text-muted-foreground">{new Date(l.logged_at).toLocaleDateString()}</span>
                    <span>{l.weight ?? '-'} kg · {l.body_fat_pct ?? '-'}% · {l.waist_cm ?? '-'} cm</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <Button onClick={exportPDF} className="w-full" size="sm">
            <Download className="h-4 w-4 mr-1" />
            Export Report
          </Button>
        </CardContent>
      </Card>
    </div>
  );
};

const Stat = ({ label, value }: { label: string; value: string }) => (
  <div className="rounded-lg border border-border p-2.5 text-center">
    <p className="text-xs text-muted-foreground">{label}</p>
    <p className="text-sm font-bold text-foreground">{value}</p>
  </div>
);

export default MedicalDashboard;
